version: '3'

services:
  emqx:
    image: emqx:latest
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"

    environment:
      EMQX_DASHBOARD_DEFAULT_USERNAME: admin
      EMQX_DAHSBOARD_DEFAULT_PASSWORD: public